language: node_js
node_js:
  - "8"
cache: npm
git:
  submodules: false
before_install:
  - git submodule update --init modules/zotero
  - git -C modules/zotero submodule update --init styles
  - git -C modules/zotero submodule update --init chrome/content/zotero/locale/csl
  - git submodule update --init modules/translators